<?php
/**
 * Authors: Alex Gusev <alex@flancer64.com>
 * Since: 2018
 */
/** @var \Magento\Backend\Block\Template $block */
?>
<div style="max-width:400px; margin:auto; width:50%; padding:10px;">
    <div style="text-align: left">
        <div><strong>CSV sample (first line will be skipped):</strong></div>
        <pre>
SOURCE ID,SOURCE_NAME,DESTINATION ID,DESTINATION_NAME,VOLUME
100002252,SALA MARIJA,100002178,ILGAZS AGRIS,750.00
100002252,SALA MARIJA,100002345,ILGAZA AIJA,750.00
</pre>
    </div>
</div>

