<?php
/**
 * Authors: Alex Gusev <alex@flancer64.com>
 * Since: 2018
 */
/** @var \Magento\Backend\Block\Template $block */
?>
<div style="max-width:300px; margin:auto; width:50%; padding:10px;">
    <div style="text-align: left">
        <div><strong>CSV sample (first line will be skipped):</strong></div>
        <pre>
"FROM",     "TO",       "VALUE"
"777016623","777044000","10.23"
"800018534","777044000","23.10"
</pre>
    </div>
</div>

